// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLOevbYN50OPfmqE_1F4j7-eSmI8xXWyw',
    appId: '1:764153029511:web:0b42cdcc5d836396776922',
    messagingSenderId: '764153029511',
    projectId: 'counterapp0',
    authDomain: 'counterapp0.firebaseapp.com',
    storageBucket: 'counterapp0.firebasestorage.app',
    measurementId: 'G-ZJVL26LYFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhhWoYZwkOeT1lZ-cW0UZqjfVybQV6Ntc',
    appId: '1:764153029511:android:d4dd0a031974d3ac776922',
    messagingSenderId: '764153029511',
    projectId: 'counterapp0',
    storageBucket: 'counterapp0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlhm3CBmlob2QTHaUm1Z1GOiFc6d_7Fzw',
    appId: '1:764153029511:ios:d47769f914e3faee776922',
    messagingSenderId: '764153029511',
    projectId: 'counterapp0',
    storageBucket: 'counterapp0.firebasestorage.app',
    iosBundleId: 'com.example.counterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlhm3CBmlob2QTHaUm1Z1GOiFc6d_7Fzw',
    appId: '1:764153029511:ios:d47769f914e3faee776922',
    messagingSenderId: '764153029511',
    projectId: 'counterapp0',
    storageBucket: 'counterapp0.firebasestorage.app',
    iosBundleId: 'com.example.counterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLOevbYN50OPfmqE_1F4j7-eSmI8xXWyw',
    appId: '1:764153029511:web:63551416d7deb7a1776922',
    messagingSenderId: '764153029511',
    projectId: 'counterapp0',
    authDomain: 'counterapp0.firebaseapp.com',
    storageBucket: 'counterapp0.firebasestorage.app',
    measurementId: 'G-G4HVFN8X13',
  );
}
